name: Unit Tests

on:
  pull_request:
    paths:
      - '**.py'
      - '**.yar'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11.4'

    - name: Install Requirements
      run: |
        pip install -r requirements.txt
        pip install .

    - name: Run Unit Tests
      run: |
        pytest
